on:
  workflow_run:
    workflows: "Init repo"
    types:
      - completed
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: write

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R libraries in renv # add packages to the renv file if you need them to render the code
        uses: r-lib/actions/setup-renv@v2

      - name: Render quarto website
        run: quarto render

      - name: Publish
        if: github.event_name != 'pull_request' # for PR the quarto will only be rendered when merged to main also published
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
          path: ./_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
